config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"
require "resque/server"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedOut.new do
    root to: "homes#show"
  end
  constraints Monban::Constraints::SignedIn.new do
    root to: "dashboards#show"
  end

  constraints ->(_request) { Rails.env.development? } do
    mount Resque::Server, at: "/jobs"
  end

  resource :session, only: %i(new create destroy)
  resources :users, only: %i(new create show) do
    member do
      post "follow" => "follows#create"
      post "unfollow" => "follows#destroy"
    end
  end

  resources :recipes, only: %i(show) do
    resources :comments, only: %i(create)
    member do
      post "like" => "likes#create"
      post "unlike" => "likes#destroy"

      post "bookmark" => "bookmarks#create"
      post "unbookmark" => "bookmarks#destroy"
    end
  end

  namespace :my do
    resources :comments, only: %i(destroy)
    resources :recipes, only: %i(new create edit destroy update)
  end

  resource :search, only: %i(show)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  protect_from_forgery with: :exception

  private

  def current_user
    super || Guest.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_nested(text, form, association)
    singular_name = association.to_s.singularize
    object = form.object.public_send(association).build

    template = form.fields_for(association, object,
                               child_index: "__ID__") do |nested_form|
      render "#{singular_name}_fields", form: nested_form
    end

    link_to text, "#", data: { role: "add-nested", template: template },
                       class: "button-light"
  end
end

app/views/application/_header.html.erb
<header>
  <nav>
    <%= link_to "Cookpad", "/", class: "button-light flex-left"%>
    <% if signed_in? %>
      <%= current_user.username %>
      <%= link_to t("my_recipes"), current_user, class: "button-light"%>
      <%= link_to t("sign_out"), session_path, method: :delete, class: "button-light" %>
    <% else %>
      <%= link_to t("sign_in"), new_session_path, class: "button-light" %>
      <%= link_to t("sign_up"), new_user_path, class: "button" %>
    <% end %>
  </nav>
</header>